---
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: docker
    release: jumpbox
  - name: jumpbox
    properties:
      docker:
        image: busybox
        volume: homedirs
      jumpbox:
        ssh_password_auth: true
        users:
          - name: platform
            shell: /bin/bash
            sudo: false
            groups: vcap
            password: "$6$T80NVKSUL4KoVyLi$LxnaYBDMjX3sR1t4bprcIh9G8uxLhacp/2ckqTJknGwResAUJaB6PVm2ZoheK0l7c9MgzWqSxXOl/Fp8sLWV/."
    release: jumpbox
  name: jumpbox
  networks:
  - name: default
  persistent_disk: 20480
  stemcell: trusty
  vm_type: default
name: jumpbox
releases:
- name: jumpbox
  version: latest
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 'latest'
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  serial: false
  update_watch_time: 1000-60000
