---
# this is a BOSH Ops file, to be applied with the
# `bosh deploy -o ...` command:
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/jumpbox?/users?/-
  value:
- name:    jumpbox
  version: 4.8.15
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.8.15/jumpbox-4.8.15.tgz
  sha1:    fa988a6b076726249bd6ab4d9872540d9c3713a6
