---
# this is a BOSH Ops file, to be applied with the
# `bosh deploy -o ...` command:
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/jumpbox?/users?/-
  value:
- name:    jumpbox
  version: 4.8.17
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.8.17/jumpbox-4.8.17.tgz
  sha1:    a2f277e0129336dbaea674fe1af4580117bb6ca4
