---
# this is a BOSH Ops file, to be applied with the
# `bosh deploy -o ...` command:
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/jumpbox?/users?/-
  value:
- name:    jumpbox
  version: 4.8.10
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.8.10/jumpbox-4.8.10.tgz
  sha1:    316b1f9c6f8be42f9ffd147e400884539a04ef81
