---
# this is a BOSH Ops file, to be applied with the
# `bosh deploy -o ...` command:
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/jumpbox?/users?/-
  value:
- name:    jumpbox
  version: 4.7.7
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.7.7/jumpbox-4.7.7.tgz
  sha1:    0e8c8c2de8cda91c89dd7b27b3e1781fd7f5227d
