---
# this is a BOSH Ops file, to be applied with the
# `bosh deploy -o ...` command:
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/jumpbox?/users?/-
  value:
- name:    jumpbox
  version: 4.8.4
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.8.4/jumpbox-4.8.4.tgz
  sha1:    7caf234f0f9a6b728ee0651cd28a95abd44f3fed
