---
# this is a BOSH Ops file, to be applied with the
# `bosh deploy -o ...` command:
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/jumpbox?/users?/-
  value:
- name:    jumpbox
  version: 4.8.7
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.8.7/jumpbox-4.8.7.tgz
  sha1:    27e5642b6173cf081d08e58b5b85c62100c37e3f
