---
# this is a BOSH Ops file, to be applied with the
# `bosh deploy -o ...` command:
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/jumpbox?/users?/-
  value:
- name:    jumpbox
  version: 4.8.5
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.8.5/jumpbox-4.8.5.tgz
  sha1:    565e5b70139adc472ee33a256e586e7587dffeb2
