---
# this is a BOSH Ops file, to be applied with the
# `bosh deploy -o ...` command:
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/jumpbox?/users?/-
  value:
- name:    jumpbox
  version: 4.7.6
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.7.6/jumpbox-4.7.6.tgz
  sha1:    9fb7167c9bd36fc0501694c18e208bf478ceb368
