---
# this is a BOSH Ops file, to be applied with the
# `bosh deploy -o ...` command:
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/jumpbox?/users?/-
  value:
- name:    jumpbox
  version: 4.8.16
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.8.16/jumpbox-4.8.16.tgz
  sha1:    58620be178ef0d6dc3578b2137c9cff9318f732f
