---
# this is a BOSH Ops file, to be applied with the
# `bosh deploy -o ...` command:
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/jumpbox?/users?/-
  value:
- name:    jumpbox
  version: 4.8.12
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.8.12/jumpbox-4.8.12.tgz
  sha1:    9afd1c01d8a11789a41d1199963d41c3494531ac
