---
# this is a BOSH Ops file, to be applied with the
# `bosh deploy -o ...` command:
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/jumpbox?/users?/-
  value:
- name:    jumpbox
  version: 4.8.6
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.8.6/jumpbox-4.8.6.tgz
  sha1:    e8ead7fea99f5419f919365a42fb157215ddbbeb
