---
# this is a BOSH Ops file, to be applied with the
# `bosh deploy -o ...` command:
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jumpbox/properties?/jumpbox?/users?/-
  value:
- name:    jumpbox
  version: 4.7.5
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.7.5/jumpbox-4.7.5.tgz
  sha1:    0f8a76ea4bc731e0c397da0773aa87475ce9f1b2
