name: jumpbox

instance_groups:
- name: jumpbox
  instances: 1
  azs:       [z1]
  stemcell:  default
  vm_resources:
    cpu: 2
    ram: 2048
    ephemeral_disk_size: 40_960
  networks:
    - name: default
  jobs:
    - { release: jumpbox, name: jumpbox }
    - { release: jumpbox, name: inventory }

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias:   default
  os:      ubuntu-xenial
           # minimum v170.x of Xenial REQUIRED
  version: latest

releases:
- name:    jumpbox
  version: 4.8.4
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.8.4/jumpbox-4.8.4.tgz
  sha1:    7caf234f0f9a6b728ee0651cd28a95abd44f3fed
