name: jumpbox-ci

instance_groups:
- name: jumpbox
  instances: 1
  azs:       [z1]
  vm_type:   default
  stemcell:  default
  networks:
    - name: default
  jobs:
    - name: jumpbox
      release: jumpbox

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: jumpbox
  version: latest
