meta:
  environment: (( param "Please set an environment string" ))
  stemcell:    (( param "Please specify a stemcell" ))

name: (( grab meta.environment ))

director_uuid: (( param "Please specify the BOSH Director UUID" ))

compilation:
  workers: 6
  network: jumpbox1
  reuse_compilation_vms: true

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: false

resource_pools:
  - name: small
    network: jumpbox1
    stemcell: (( grab meta.stemcell ))
