meta:
  dns_root: (( param "Please specify a root DNS name" ))
  security_groups: (( param "Please define Security Groups" ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: jumpbox
    instances: 1
    networks:
      - name: jumpbox1
    persistent_disk: (( grab meta.persistent_disk ))


compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: jumpbox1
    type: dynamic
    cloud_properties:
      security_groups: (( grab meta.security_groups ))
