meta:
  environment: jumpbox-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: jumpbox
    instances: 1
    networks:
      - name: jumpbox1
        static_ips: (( static_ips 0 ))

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small
    cloud_properties:
      name: random

networks:
- name: jumpbox1
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.102.0/24
    reserved:
    - 10.244.102.1
    static:
    - 10.244.102.2 - 10.244.102.50
