meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: jumpbox_z1
    instances: 1
    templates:
      - { release: jumpbox, name: jumpbox }
    networks:
      - name: jumpbox1
    resource_pool: small_z1
    persistent_disk: 10240

  - name: acceptance-tests
    lifecycle: errand
    instances: 1
    templates:
      - { release: jumpbox, name: acceptance-tests }
      - { release: jumpbox, name: jumpbox }
    networks:
      - name: jumpbox1
    resource_pool: small_z1

properties:
  jumpbox:
    env:
      FOO: BAR
    users:
      - name: alice
      - name: bob
      - name: eve
        shell: /bin/sh
    delete:
      - chris
