meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: jumpbox_z1
    template: jumpbox
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 10240
    properties: {}

networks: (( merge ))

properties:
  jumpbox:
    env:
      FOO: BAR
    users:
      - name: alice
      - name: bob
      - name: eve
        shell: /bin/sh
    delete:
      - chris
