---
meta:
  name: jumpbox-boshrelease
  target: starkandwayne
  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))
  github:
    owner: cloudfoundry-community
    repo:  jumpbox-boshrelease
    private_key:  (( vault "secret/pipelines/jumpbox-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/jumpbox-boshrelease/github:token" ))
  bosh-lite:
    target: https://10.58.111.44:25555
  slack:
    webhook: (( vault "secret/pipelines/jumpbox-boshrelease/slack:webhook" ))
    channel: "#cf-community-pipeline"
